# Generated by Django 4.1.7 on 2023-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userfavorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorites',
            name='item',
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='item',
            field=models.ManyToManyField(to='base.product'),
        ),
    ]
