# Generated by Django 4.1.7 on 2023-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_userfavorites_item_userfavorites_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(to='base.product'),
        ),
    ]
