# Generated by Django 4.1.7 on 2023-03-31 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_userprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Perfume'), ('J', 'Jewellery'), ('C', 'Cosmetics')], max_length=10),
        ),
    ]
