# Generated by Django 4.1.7 on 2023-03-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userprofile_slug_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
