# Generated by Django 4.1.7 on 2023-04-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.discountcode'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='coupon',
            field=models.CharField(max_length=15),
        ),
    ]
