# Generated by Django 4.1.7 on 2023-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_coupon_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='OPASNO'),
            preserve_default=False,
        ),
    ]
