# Generated by Django 4.1.7 on 2023-04-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_description_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
