# Generated by Django 4.1.7 on 2023-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_userprofile_sale_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_code',
            field=models.CharField(default='P1111', max_length=8),
            preserve_default=False,
        ),
    ]
