# Generated by Django 4.1.7 on 2023-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_image_code_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='front_image',
            field=models.CharField(default='asd', max_length=8),
            preserve_default=False,
        ),
    ]
