# Generated by Django 4.1.7 on 2023-04-14 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 4, 14)),
        ),
    ]
