# Generated by Django 4.1.7 on 2023-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_product_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlights', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.ManyToManyField(blank=True, to='base.perfumehighlights'),
        ),
    ]
