# Generated by Django 4.1.7 on 2023-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincarecategory',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('NC', 'Night Creams'), ('FO', 'Face Oils'), ('MNE', 'Mists and Essences')], max_length=20),
        ),
    ]
