# Generated by Django 4.1.7 on 2023-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_skincarecategory_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skincarecategory',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_skincare_category',
            field=models.CharField(blank=True, choices=[('NC', 'Night Creams'), ('FO', 'Face Oils'), ('MNE', 'Mists and Essences')], max_length=10),
        ),
    ]
