# Generated by Django 4.1.7 on 2023-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_product_sub_skincare_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='makeup_category',
            field=models.CharField(blank=True, choices=[('E', 'Eye'), ('F', 'Face'), ('L', 'Lip')], max_length=10),
        ),
    ]
