# Generated by Django 4.1.7 on 2023-04-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='product',
        ),
    ]
