# Generated by Django 4.1.7 on 2023-04-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_billingaddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
