# Generated by Django 4.1.7 on 2023-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_billingaddress_apartment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
